guest_list = ['Agnes', 'Agatha', 'Germaine', 'Jack']
print(f"{guest_list[0]}, would you like to come to dinner?")
print(f"{guest_list[1]}, would you like to come to dinner")    
print(f"{guest_list[2]}, would you like to come to dinner?")
print(f"{guest_list[-1]}, would you like to come to dinner?")     
print(f"Oh shit! {guest_list[2]} can't make it! We'll invite Michael instead")
guest_list.remove('Germaine')
guest_list.insert(2,'Michael')
print(f"{guest_list[0]}, would you like to come to dinner?")
print(f"{guest_list[1]}, would you like to come to dinner")    
print(f"{guest_list[2]}, would you like to come to dinner?")
print(f"{guest_list[-1]}, would you like to come to dinner?")     
print("A bigger table is now available!!!")
guest_list.insert(0,'Jenny')
guest_list.insert(3,'Tabatha')
guest_list.append("George")
print(guest_list)
print("Doh! They only have a table for two!")
uninvited_guest=guest_list.pop(2)
print(f"Sorry {uninvited_guest}, you gots to go!")
print (guest_list)
uninvited_guest=guest_list.pop(-1)
print(guest_list)
guest_list.remove("Jenny")
print(guest_list)
guest_list.remove("Agnes")
guest_list.remove("Jack")
print(guest_list)
del guest_list[0]
del guest_list[0]
print (guest_list)